package com.rootscare.serviceprovider.ui.physiotherapy.appointmentlist

import com.rootscare.serviceprovider.ui.base.BaseViewModel

class FragmentPhysiotherapyAppointmentListViewModel : BaseViewModel<FragmentPhysiotherapyAppointmentListNavigator>()