package com.rootscare.serviceprovider.ui.babySitter.babySitterAppointment.babySitterAppointmentDetails

import com.rootscare.serviceprovider.ui.babySitter.babySitterAppointment.babySitterAppointmentDetails.FragmentBabySitterAppointmentDetailsNavigator
import com.rootscare.serviceprovider.ui.base.BaseViewModel

class FragmentBabySitterAppointmentDetailsViewModel: BaseViewModel<FragmentBabySitterAppointmentDetailsNavigator>() {
}