package com.rootscare.serviceprovider.ui.caregiver.caregigerreviewandrating

import com.rootscare.serviceprovider.ui.base.BaseViewModel
import com.rootscare.serviceprovider.ui.nurses.nursesreviewandrating.FragmentNursesReviewAndRatingNavigator

class FragmenntCaregiverReviewAndRatingViewModel: BaseViewModel<FragmenntCaregiverReviewAndRatingNavigator>() {
}